language: python
python:
- '3.6'
services:
- mongodb
install:
- pip install -r requirements_dev.txt
script:
- pytest
deploy:
  provider: pypi
  user: map
  password:
    secure: gSOxNAilyXb7qp/acnsqvvIRUNdBy1x8wqnTifiOr/jqRm2jN5J/kKSFWtQzx0TJAnY4713/HnNL52QGWoya8zTJ7kQiOgZrTczYtwOpUORSoUhJl9UI8syoZtZ61Vkmu8llpgkgXwqfkgrQwKPy5zQIl9ss+Az1bB98QISyrpmJSn8NM5XMl3sNrdpHxfQT1/4T3WyxEpbrLtNlcBlB/RGwaCUAvv2NcD7zeV+IPl87fX5n9p9N5ZfhyBS3Oc22yF7RoYnIV++uNdtYAIOdauE6B40hP7yBkdrUhVKbK+c8CjHbWfGxWYWZ88vNUEo/H9nqUhqT0oPmlhzqDqe2NDQLtvGyuYA4Dlu7xQ9v8awElHVFOrW49CC8hRAIoRe/hgvfGjvrmasg5lHWqUCj0+rD0I/BspRaXVaS52mADGDjEfqkOVqDgyrAOXDNrJXC95Rr0op3bI3jWGDQGS3ezPE292I30f2Uyz0GzOe7dCBq+WVx9Nu0OC5ILeC9BrSy69zk33cT7Ot6g0O2rrS0v+5OPb75XgA9u+yCULkM5NKyf4m+3MuDk00jTe7fSG6JGXT2VaPcgIDroqL9XRJgsa+AAxSii+FJPzDvmlaaU2GX1JS1BCACjE5EC8I/FHGDfypwA0lIL88C7xlgdeJTrAT/lZIWvA3ITwRuDMVZLTo=
  on:
    tags: true
    branch: master
